name: hello work

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "running test..."
        shell: bash

